server:
  port: 8000
  servlet:
    # 프로젝트에 들어가기 위한경로
    # localhost:8000/blog/http/lombok 이런식으로 작성 해야 함     
    context-path: /blog 
    encoding:
      charset: UTF-8
      enabled: true
      force: true
    
spring:
  mvc:
    view:
      prefix: /WEB-INF/views/ 
      #  controller가 리턴할 때 앞에 붙이는 
      suffix: .jsp
      
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: dbc:mysql://localhost:3306/blog?serverTimezone=Asia/Seoul
    username: lollolzz1018
    password: tkfka1704!
    
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: create
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      use-new-id-generator-mappings: false
    show-sql: true
    properties:
      hibernate.format_sql: true

  jackson:
    serialization:
      fail-on-empty-beans: false
